prod:
  image: vizzuality/gfw-user-api:1.0.0
  ports:
    - "3100"
  env_file:
    - prod.env
  command: start
  restart: always
  log_driver: "gelf"
  log_opt:
    gelf-address: "udp://172.31.40.76:12201"
